config/routes.rb
Rails.application.routes.draw do

	get '/login/show/:id', to: 'logins#show', as: 'login_show'

	get 'problems/index'

  resources :problems do
    get :close, on: :member
	  resources :notes, :shallow => true do
      get :choose, on: :member
    end
  end

  resources :users, :only => [:new, :create]
  resource :login, :only => [:new, :create, :destroy, :show]

	get 'users/activate/:activation_key' => 'users#activate', as: :activate_user
	patch 'users/activate' => 'users#update'

  root 'problems#index'

end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :user
	belongs_to :problem

  after_create :send_email

  validates :comment, presence: true
  validates :problem, presence: true
  validates :user, presence: true

  validate :check_one_chosen_note_per_problem

  def check_one_chosen_note_per_problem
    return unless problem.present?

    if problem.resolved && self.chosen?
      errors.add(:chosen, "cannot be chosen because there is already a chosen note for that problem")
    end
  end

  def send_email
    if self.user != self.problem.user
      UserMailer.new_note(self.id).deliver
    end
  end
end

app/models/problem.rb
class Problem < ActiveRecord::Base
  belongs_to :user
  has_many :notes

  validates :issue, presence: true
  validates :try, presence: true
  validates :user, presence: true

  after_create :send_email

  def note_count
    notes.count
  end

  def send_email
    UserMailer.new_problem(self.id).deliver
  end
end

app/models/user.rb
require 'securerandom'

class User < ActiveRecord::Base
	before_validation :set_key
	after_create :send_email

	has_many :problems
	has_many :notes

	validates :name, presence: true

	validates :email,
	          presence: true,
	          uniqueness: { case_sensitive: false },
	          format: { with: /\A[\w\-\.]+@[\w\-\.]+\Z/, message: "must be a valid email address" }

	has_secure_password

	def set_key
		self.activation_key = SecureRandom.uuid
	end

	def send_email
		UserMailer.account_activation(id).deliver
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  add_flash_types :success, :info

  private

  def current_user
	  @current_user ||= User.find_by(id: session[:current_user_id])
  end

  def logged_in?
	  !!current_user
  end

  def authenticate
	  unless logged_in?
		  redirect_to new_login_path, warning: "Please sign in."
	  end
  end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
	def new
	end

	def create
		@user = User.find_by(email: params[:email])

		if @user && @user.authenticate(params[:password])
			if @user.activated
				session[:current_user_id] = @user.id
				redirect_to root_path, success: "You are successfully logged in."
			else
        flash.now[:info] = "You have not been logged in."
        render :show
			end
		else
			flash.now[:alert] = "Your email and password were invalid."
      render :new
    end
	end

	def destroy
		session[:current_user_id] = nil
		redirect_to root_path, success: "You have been logged out."
	end

	def show
		@user = User.find(params[:id])
	end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :authenticate
  before_action :set_note, only: [:destroy, :update, :choose]

  def index
    @notes = Note.all
  end
  def new
    @note = Note.new
  end
  def show
  end

  def create
    @problem = Problem.find(params[:problem_id])
    @note = current_user.notes.build(note_params)
    @note.problem = @problem

  respond_to do |format|
    format.html do
    if @note.save
      redirect_to @problem, success: "Note created."
    else
      redirect_to @problem
    end
  end

    format.js do
        if @note.save
          render "notes/create", status: :created
        else
          render nothing: true, status: :bad_request
        end
      end
    end
  end

  def destroy
    if @note.destroy
      redirect_to @note.problem
    end
  end

  def update
  end

  def choose
    @problem = @note.problem

    if @note.update(chosen: true) && @problem.update(resolved: true)
      redirect_to @problem, success: "Problem has been closed and removed from open problems list."
    else
      redirect_to @problem
    end
  end

  private

  def note_params
    params.require(:note).permit(:user, :comment, :chosen, :name)
  end

  def set_note
		@note = Note.find(params["id"])
  end

end

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController
  before_action :authenticate, only: [:new, :create, :destroy, :close, :update]
  before_action :set_problem, only: [:show, :update, :destroy, :close]

  def index
    @problems = Problem.where(resolved: false).order('created_at DESC')
    @problem = Problem.where(resolved: false).order('created_at DESC')


  end

  def show
    @notes = @problem.notes
    @note = Note.new
  end

  def new
    @problem = Problem.new
  end

  def create
    @problem = current_user.problems.build(problem_params)

    if @problem.save
      redirect_to @problem, notice: 'Problem was successfully created.'
    else
      render :new
    end
  end

  def update
    if @problem.update(problem_params)
      redirect_to @problem, notice: 'Problem was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    if @problem.destroy
      redirect_to problems_url, notice: 'Problem was successfully destroyed.'
    end
  end

  def close
    # if @problem.update(resolved: true)
      respond_to do |format|

      format.html do
        if @problem.update(resolved: true)
        redirect_to @problem, success: "Problem has been closed and removed from the open problems list."
      else
          redirect_to @problem
      end
    end

    format.js do
      if @problem.update(resolved: true)
      render "problems/destroy", status: :destroyed
    else
        redirect_to @problem
    end
  end
end
end


  private

  def set_problem
    @problem = Problem.find(params[:id])
  end

  def problem_params
    params.require(:problem).permit(:issue, :try)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)

		if @user.save
			redirect_to login_show_path(@user), success: "Thank you for registering."
		else
			render :new
		end

	end

	def activate
		if valid_key?
			@user.update(activated: true)
			redirect_to login_show_path(@user), success: "User account successfully activated."
		else
			render :show, error: "User activation failed. Please double check email or request new activation key."
		end
	end

	private

	def valid_key?
		@user = User.find_by(activation_key: params[:activation_key])
	end

	def user_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/problems_helper.rb
module ProblemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <title>I Need Help!</title>
  <!--  content_for?(:title) ? yield(:title) : "foundation-rails"  -->
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "vendor/modernizr" %>
  <%= csrf_meta_tags %>
</head>

<body>

<%= render 'shared/nav' %>
<%= render 'shared/flash' %>

<%= yield %>
<%= javascript_include_tag "application" %>
</body>
</html>

app/views/logins/new.html.erb
<div class="row">

  <div class="small-10 small-offset-1 columns">

    <h1>Login or <%= link_to 'register', new_user_path %></h1>

    <%= form_tag login_path, :method => :post do %>

        <%= label_tag :email %>
        <%= text_field_tag :email %>

        <%= label_tag :password %>
        <%= password_field_tag :password %>

        <%= button_tag "Log in" %>

    <% end %>

  </div>

</div>

app/views/logins/show.html.erb
<div class="row">
  <div class="small-10 small-offset-1 columns">

    <% if @user.try(:activated) %>
        <p>Thank you <%= @user.name.capitalize %> for activating your account.  Please <%= link_to 'login', new_login_path %> to use Lab6.</p>
    <% else %>
        <p>Before you can use your account, please check your email and follow the instructions to activate your account.</p>
    <% end %>

    <p>
      <%= link_to "Go to homepage", root_path %>
    </p>

  </div>
<div>

app/views/notes/_note.html.erb
<div class="row" id="<%= note.persisted? ? dom_id(note) : "note-new" %>">
  <div class="panel">
    <div><%= note.comment %></div>
    <div>Answered by <%= note.user.name %></div>
  </div>
</div>

app/views/notes/create.js.erb
$("#notes").append("<%= j render(@note) %>");

app/views/problems/_form.html.erb
<%= form_for(@problem) do |f| %>
  <% if @problem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@problem.errors.count, "error") %> prohibited this problem from being saved:</h2>

      <ul>
      <% @problem.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<%= f.text_area :issue, placeholder: "What's your Problem?" %>
<%= f. text_area :try, placeholder: "What were your Solutions?" %>

<%= f.button 'Add Problem', class: "btn btn-large btn-success" %>

<% end %>

app/views/problems/_problem.html.erb
<div class="row" id="<%= problem.persisted? ? dom_id(problem) : "problem-close" %>">
  <div class="panel">
    <div><%= link_to truncate(problem.issue, length: 140, omission: "...(continued)"), problem_path(problem) %></div>
    <div>Asked by <%= problem.user.name %> on
      <%= l problem.created_at.in_time_zone('Eastern Time (US & Canada)'), format: :asked %>
      | <%= pluralize(problem.note_count, 'note') %> posted</div>
  </div>
  <p>
        <% if problem.resolved == false %>
          <% if current_user == problem.user %>
            <%= link_to 'Mark as resolved <i class="fa fa-check-square"></i>'.html_safe, close_problem_path(problem.id), remote: true %>
          <% else %>
            <strong>Open Problem</strong>
          <% end %>
        <% else %>
          <strong>Closed Problem</strong>
        <% end %>
      </p>

      <p>
        Asked by <%=problem.user.name %>
      </p>

    </div>

app/views/problems/destroy.js.erb
$("#problems").append("<%= j render (@problem) %>");
$("#problems").remove();

app/views/problems/edit.html.erb
<h1>Editing problem</h1>

<%= render 'form' %>

<%= link_to 'Show', @problem %> |
<%= link_to 'Back', problems_path %>

app/views/problems/index.html.erb
<div class="row">

  <div class="small-10 small-offset-1 columns">

    <h3>Open Problems</h3>

	<% if !logged_in? %>
		<p>To add your own problem, please <%= link_to 'login', new_login_path %>.</p>
	<% end %>

	</div>
</div>
<div class="row">
  <div id="problems">
  <%= render @problems %>
</div>

</div>




</div>

app/views/problems/new.html.erb
<div class="row">
  <div class="small-10 small-offset-1 columns">

    <h1>New problem</h1>

		<%= render 'form' %>

	</div>
</div>

app/views/problems/show.html.erb
<div class="row">
  <div class="small-10 small-offset-1 columns">

		<div class="row">

			<p>
			  <strong>The Issue I'm Having:</strong>
			  <%= @problem.issue %>
			</p>

			<p><strong>What I've Tried:</strong>
			  <%= @problem.try %>
			</p>

			<p>
				<% if @problem.resolved == false %>
				  <% if current_user == @problem.user %>
					  <%= link_to 'Mark as resolved <i class="fa fa-check-square"></i>'.html_safe, close_problem_path(@problem) %>
					<% else %>
						<strong>Open Problem</strong>
					<% end %>
				<% else %>
					<strong>Closed Problem</strong>
				<% end %>
			</p>

			<p>
			  Asked by <%=@problem.user.name %>
			</p>

		</div>



<div id="notes">
	<%= render @notes %>
  </div>

		<div class="row">

			<% if logged_in? %>
			  <fieldset>
			    <legend>Add a Note:</legend>
					  <%= simple_form_for [@problem, @note], remote: true do |form| %>
          <%= form.input :comment %>
          <%= form.button :submit, "Add Note", class: "radius" %>
        <% end %>
			  </fieldset>
			<% else %>
				To add a note, please <%= link_to "login", new_login_path %>
			<% end %>
		</div>

	</div>
</div>

app/views/shared/_flash.erb
<% flash.each do |key, msg| %>
  <%= content_tag :div, msg, :class => "alert-box " + key %>
<% end %>

app/views/shared/_nav.html.erb
<nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to 'I Need Help!', root_path %></a></h1>
    </li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <% if logged_in? %>
        <li><a>Logged in as <%= current_user.name %></a></li>
        <li class="divider"></li>
        <li><%= link_to "Logout", login_path, :method => :delete %></li>
      <% else %>
        <li><%= link_to "Login", new_login_path %></li>
      <% end %>

      <% if logged_in? %>
        <li class="divider"></li>
	      <li class="has-form">
	        <%= link_to "New Problem", new_problem_path, :class => "button" %>
	      </li>
		  <% end %>
    </ul>

    <!-- Left Nav Section -->
    <ul class="left">
      <li class="divider"></li>
      <li><%= link_to 'All problems', problems_path %></li>
    </ul>
  </section>
</nav>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<div class="row">

  <h1>Register or <%= link_to 'login', new_login_path %></h1>

  <%= form_for(@user) do |f| %>

      <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name %>
      </div>

      <div class="field">
        <%= f.label :email %>
        <%= f.text_field :email %>
      </div>

      <div class="field">
        <%= f.label :password %>
        <%= f.password_field :password %>
      </div>
      <div class="field">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation %>
      </div>
      <div class="actions">
        <%= button_tag "Join" %>
      </div>

  <% end %>

</div>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>